### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Ahmed2406186** [mohammed-saleh2007/c-counter#1]
Whhhy!

**Comment by mohammed-saleh2007** [comment]
check out my stuff:
![image](https://github.com/mohammed-saleh2007/c-counter/assets/140978153/7be24eec-1bfd-4feb-89a4-4cae0106da4e)

**Comment by mohammed-saleh2007** [comment]
[https://github.com/mohammed-saleh2007/oddoreven](https://github.com/mohammed-saleh2007/oddoreven?fbclid=IwAR1ALhTb2phWEKMYUpwxA3r8biQnKW9C6L4Gzn4BXsnYtIItMIc8f8VbMHQ)
